Cosmetic Changes Search Functionality and Highlight, Comments UI, Save UI, DB calls
crowdedpoem/Sager pull request #7
Opened 2024-02-13 20:49 UTC by santheman12

2024-02-14 17:25 UTC, crowdedpoem commented on lib/calls.tsx
> +        const queryLower = query.toLowerCase();
I was wondering about this. I think there should be a file called `libs/normalize/ts` where we specify how we will trim whitespace and make text case insensitive before adding to the database

2024-02-14 17:53 UTC, crowdedpoem commented on src/components/SearchServerParams.tsx
> +        setInputValue(searchQuery.toLowerCase());
another place to use `libs/normalize.ts`

2024-02-14 18:04 UTC, crowdedpoem requested changes
Overall, really good. Just would like to see a `libs/normalization.ts` library function that normalizes input for the database. It would improve search reliability greatly. Also, maybe handle dates with built in libraries

2024-02-15 20:28 UTC, santheman12 commented
> Overall, really good. Just would like to see a `libs/normalization.ts` library function that normalizes input for the database. It would improve search reliability greatly. Also, maybe handle dates with built in libraries

will need to format the date on the postCard as well, but will wait for the merging to be complete for that

2024-02-15 22:35 UTC, crowdedpoem approved these changes

2024-02-15 23:11 UTC, merged